{% set name = "opentelemetry-exporter-jaeger-proto-grpc" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_jaeger_proto_grpc-{{ version }}.tar.gz
  sha256: 4dea9bdd4f295aa497d1dcf5ecdab480b4ddffca59d9a8f06f475595a37c9be9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - googleapis-common-protos <1.56.3,~=1.52
    - grpcio <2.0.0,>=1.0.0
    - opentelemetry-api ~=1.3
    - opentelemetry-sdk ~=1.11

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter
    - opentelemetry.exporter.jaeger
  commands:
    # The conda forge pinnings for googleapis-common-protos are less strict than pip so ignore this for now
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-jaeger-proto-grpc
  summary: Jaeger Protobuf Exporter for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
